#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Python 3 (ipykernel)
# Python: 3.11.7
# Cells: 98 code, 42 markdown

# ────────────────────────────────────────────────────────────────────────
# ## 01 Escribe una función que reciba una cadena de texto como parámetro y devuelva un diccionario con las frecuencias de cada letra en la cadena. Los espacios no deben ser considerados. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [3]

from functools import reduce

# ────────────────────────────────────────────────────────────────────────
# %%  [134]

def contar_letras(cadena : str) -> dict[str, int]:
    
    frecuencias = dict() # dicionario vacio
    
    for letra in cadena:
        if letra != " ": # evitar contar espacios de la cadena de texto
            letra = letra.lower() 
            if letra in frecuencias: # si la letra está en el diccionario suma 1 al valor
                frecuencias[letra] += 1
            else:
                frecuencias[letra] = 1 # si no se encunetra crea unaclave con la letra y valor 1
                
    return frecuencias
    


# ────────────────────────────────────────────────────────────────────────
# %%  [132]

texto = "Hola que tal todo"

contar_letras(texto)


# ────────────────────────────────────────────────────────────────────────
# ## 02 Dada una lista de números, obtén una nueva lista con el doble de cada valor. Usa la función map() ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [4]

lista = [1,2,3,4,5,6,7,8,9,10]


# ────────────────────────────────────────────────────────────────────────
# %%  [5]

lista_doble = list(map(lambda x: x*2, lista))
print(lista_doble)

# ────────────────────────────────────────────────────────────────────────
# ## 03 Escribe una función que tome una lista de palabras y una palabra objetivo como parámetros. La función debe devolver una lista con todas las palabras de la lista original que contengan la palabra objetivo. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [137]

def fam_semantica(lista: list[str],objetivo: str) -> list[str]: 
    resultado = []
    
    for palabra in lista:
        if objetivo in palabra:
            resultado.append(palabra)

    return resultado
        


# ────────────────────────────────────────────────────────────────────────
# %%  [138]

lista = ("amar", "mama", "amarre", "amable", "amado", "mar" , "palabras", "amistad", "barra")

fam_semantica(lista, "ama")

# ────────────────────────────────────────────────────────────────────────
# ## 04 Genera una función que calcule la diferencia entre los valores de dos listas. Usa la función map() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [159]

def diferencia_listas(x: list[int], y: list[int]) -> list[int]:
"""Función para restar los elementos de dos listas dadas """
    return list(map(lambda x, y: x - y, x, y)) # map aplica la funcion (x-y) a cada elemento de la lista


# ────────────────────────────────────────────────────────────────────────
# %%  [160]

lista_1 = (1, 2, 3, 4, 5, 6, 7, 8, 9)
lista_2 = (2, 3, 4, 5, 6, 7, 8, 9, 10)

# ────────────────────────────────────────────────────────────────────────
# %%  [161]

diferencia_listas(lista_1, lista_2)

# ────────────────────────────────────────────────────────────────────────
# ## 05 Ecribe una función que tome una lista de números como parámetro y un valor opcional nota_aprobado, que por defecto es 5. La función debe calcular la media de los números en la lista y determinar si la media es mayor o igual que nota aprobado. Si es así, el estado será "aprobado", de lo contrario, será "suspenso". La función debe devolver una tupla que contenga la media y el estado. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [165]

def media_aprobada (lista: list[int], nota_aprobado = 5) -> tuple[float, str]:
    """Evalua la media de los números de una lista. 
    Si la media es mayor a la nota aprobado (por defecto 5) da aprobado sino devuelve suspenso """
   
    suma_total = sum(lista)

    resultado = round(suma_total / len(lista),2)

    if resultado >= nota_aprobado:
        estado = "Aprobado"
    else:
        estado = "Suspenso"

    
    return (resultado, estado)
        


# ────────────────────────────────────────────────────────────────────────
# %%  [166]

lista = (5, 7, 7, 8, 7, 3, 5, 6, 6, 5, 4, 3, 3, 3, 1)

media_aprobada(lista)

# ────────────────────────────────────────────────────────────────────────
# ## 06 Escribe una función que calcule el factorial de un número de manera recursiva. ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [169]

def factorial(x:int) -> int:
    if x == 0 or x == 1: # el factorial de 0 y de 1 es 1
        return 1
    else:
        return x * factorial(x - 1) # devuelve el valor de x multiplicado por el valor del factoria de x -1, el cual calcula de manera recursiva

# ────────────────────────────────────────────────────────────────────────
# %%  [170]

factorial(5)

# ────────────────────────────────────────────────────────────────────────
# ## 07 Genera una función que convierta una lista de tuplas a una lista de strings. Usa la función map () ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [15]

def tupla_to_str (tupla):
    return list(map(str,tupla))

# ────────────────────────────────────────────────────────────────────────
# %%  [16]

lista= ([(1, 2), (3, 4), (5, 6)])

tupla_to_str(lista)

# ────────────────────────────────────────────────────────────────────────
# ## 08 Escribe un programa que pida al usuario dos números e intente dividirlos. Si el usuario ingresa un valor no numérico o intenta dividir por cero, maneja esas excepciones de manera adecuada. Asegúrate de mostrar un mensaje indicando si la división fue exitosa o no. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [180]

try:

    n1 = float(input(f"por favor introduce el numerador:"))
    n2 = float(input(f"por favor introduce el denominador:"))
    
    resultado = round(n1/n2,2)

except ZeroDivisionError:

    print("No se puede dividir entre 0")

except ValueError:
    
    print("Por favor, introduce valores numéricos")

else:
    print(f"El valor de la división es {resultado}")


# ────────────────────────────────────────────────────────────────────────
# ## 09 Escribe una función que tome una lista de nombres de mascotas como parámetro y devuelva una nueva lista excluyendo ciertas mascotas prohibidas en España. La lista de mascotas a excluir es ["Mapache", "Tigre", "Serpiente Pitón", "Cocodrilo", "Oso"].Usa la función filter() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [38]

def lista_mascotas (animales: list[str]) -> list[str]:
    """Esta función elimina de una lista de nombre de animales aquellos que no se consideran mascotas """
    
    mascotas_prohibidas = ["Mapache", "Tigre", "Serpiente Pitón", "Cocodrilo", "Oso"] 

    return f"Los animale permitidos como mascota son: {list(filter(lambda mascotas: mascotas not in mascotas_prohibidas, animales))}" 
    # return valora si los nombres de la lista de animales están en la lista de animales prohibidos, devuelve aquellos valores TRUE, es decir los nombres que no aparecen en la lista.



# ────────────────────────────────────────────────────────────────────────
# %%  [39]

lista_animales = ["Perro", "Gato", "Pajaro", "Tigre"]

lista_mascotas(lista_animales)


# ────────────────────────────────────────────────────────────────────────
# ## 10 Escribe una función que reciba una lista de números y calcule su promedio. Si la lista está vacía, lanza una excepción personalizada y maneja el error adecuadamente. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [177]

def media_lista (lista: list[float]) -> float:
    
    try:
        suma_total = sum(lista)
    
        resultado = round(suma_total / len(lista),2)

        return (resultado)

    except ZeroDivisionError:
    
        return print("Por favor, añada una lista con valores")
    


# ────────────────────────────────────────────────────────────────────────
# %%  [178]

lista = [2, 5, 5]

# ────────────────────────────────────────────────────────────────────────
# %%  [179]

media_lista(lista)

# ────────────────────────────────────────────────────────────────────────
# ## 11 Escribe un programa que pida al usuario que introduzca su edad. Si el usuario ingresa un valor no numérico o un valor fuera del rango esperado (por ejemplo, menor que 0 o mayor que 120, maneja las excepciones adecuadamente. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [25]

while True:
    try:
        
        edad = float(input("Introduce tu edad: "))

        if 0 <= edad <= 120:
            break
        else:
            print("Por favor, introduzca una edad real.")
            
    except ValueError:
        
        print("Por favor, introduzca un valor numérico")
    


# ────────────────────────────────────────────────────────────────────────
# ## 12 Genera una función que al recibir una frase devuelva una lista con la longitud de cada palabra. Usa la función map() ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [181]

def letras_frase (frase: str) -> list[int]:
    
    palabras = frase.split() #crea una lista con las palabras de la frase separadass 
        
    return list(map(len, palabras)) # calcula las letras de cada palabra con len. Map aplica len a cada palabra de la lista


# ────────────────────────────────────────────────────────────────────────
# %%  [182]

frase = "Buenos días mundo"
letras_frase(frase)

# ────────────────────────────────────────────────────────────────────────
# ## 13 Genera una función la cual, para un conjunto de caracteres, devuelva una lista de tuplas con cada letra en mayúsculas y minúsculas. Las letras no pueden estar repetidas .Usa la función map() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [196]

def min_masc (caracteres: str) -> list[tuple[str, str]]:
    caracteres = set(caracteres) # set separa los caracteres en elementos
    caracteres = filter(lambda x: x != " ", caracteres)
    return list(map(lambda x: (x.upper(), x.lower()), caracteres))

# ────────────────────────────────────────────────────────────────────────
# %%  [199]

lista = ("Hola")
print (min_masc(lista))

# ────────────────────────────────────────────────────────────────────────
# ## 14 Crea una función que retorne las palabras de una lista de palabras que comience con una letra en especifico. Usa la función filter() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [234]

def comienzo_palabras (lista: list[str], letra: str) -> list[str]:

    letra = letra.lower()
    return list(filter(lambda palabra: palabra.startswith(letra), lista))
        
    

# ────────────────────────────────────────────────────────────────────────
# %%  [235]

lista = ["Avión", "árbol", "cabeza", "pez", "centauro"]

print(comienzo_palabras(lista, "c"))

# ────────────────────────────────────────────────────────────────────────
# ## 15 Crea una función lambda que  sume 3 a cada número de una lista dada ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [236]

lista = (5, 3, 2, 65, 62)

list(map(lambda x: x + 3, lista))

# ────────────────────────────────────────────────────────────────────────
# ## 16 Escribe una función que tome una cadena de texto y un número entero n como parámetros y devuelva una lista de todas las palabras que sean más largas que n. Usa la función 

# ────────────────────────────────────────────────────────────────────────
# %%  [33]

def funcion_16 (texto: str, num: int) -> list[str]:

    palabras = texto.split() # crea una lista separando el str en elementos
    
    return list(filter(lambda palabra: len(palabra) > num, palabras)) # devuelve aquellos valores TRUE de la lista palabras, aquellos mayore a num


# ────────────────────────────────────────────────────────────────────────
# %%  [34]

lista = "Hoy puede ser un día maravilloso"

funcion_16(lista, 2)

# ────────────────────────────────────────────────────────────────────────
# ## 17 Crea una función que tome una lista de dígitos y devuelva el número correspondiente. Por ejemplo, 5,7,2 corresponde al número quinientos setenta y dos 572. Usa la función reduce() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [35]

def código (lista):
    acum = 0

    for num in lista:
        
        acum = acum*10 + num


    return acum

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

def código (lista: list[int]) -> int:
    
    return reduce(lambda acum, x: acum*10 + x, lista) # reduce va recorriendo cada nº de la lista. dandole valor acum al primer valor y x al segundo
    
    

# ────────────────────────────────────────────────────────────────────────
# %%  [4]

lista = (1, 4, 6)

código(lista)

# ────────────────────────────────────────────────────────────────────────
# ## 18 Escribe un programa en Python que cree una lista de diccionarios que contenga información de estudiantes 
#  (nombre, edad, calificación) y use la función filter para extraer a los estudiantes con una calificación mayor o igual a 
#  90. Usa la función filter()

# ────────────────────────────────────────────────────────────────────────
# %%  [7]

def reg_alumno(nombre: str, edad: int, calificación: int) -> list[dict]:
    alumnos = []
    alumnos.append(
        {"Nombre": nombre,
         "Edad": edad,
         "Calificación": calificación}
    )

    return f"El alumno {nombre} ha sido registrado."

# ────────────────────────────────────────────────────────────────────────
# %%  [8]


reg_alumno("Juan", 30, 90)
reg_alumno("Alberto", 25, 87)
reg_alumno("Sofía", 27, 100)
reg_alumno("María F", 28, 90)
reg_alumno("Alejandro", 29, 70)
reg_alumno("Estefanía", 29, 86)
reg_alumno("María G", 27, 92)

# ────────────────────────────────────────────────────────────────────────
# %%  [9]

def filter_alumnos(nota: str, lista: list[dict]) -> list[dict]:
    """Filtra la lista de diccionarios por aquellos diccionarios donde el valor de la clave calificación sea mayor a nota"""
    return list(filter(lambda alumno: alumno["Calificación"] >= nota, lista))

# ────────────────────────────────────────────────────────────────────────
# %%  [10]

filter_alumnos(90, alumnos)

# ────────────────────────────────────────────────────────────────────────
# ## 19 Crea una función lambda que filtre los números impares de una lista dada ##

# ────────────────────────────────────────────────────────────────────────
# %%  [42]

lista_numeros = [4, 6, 3, 1, 7, 8]
impares = list(filter(lambda x: x % 2 != 0, lista_numeros))

print(impares)

# ────────────────────────────────────────────────────────────────────────
# ## 20 Para una lista con elementos tipo integer y string obtén una nueva lista sólo con los valores int. Usa la función filter() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [43]

lista = [1, "hola", 45, "Caraculo", 5]

list(filter(lambda x: isinstance(x, int), lista))


# ────────────────────────────────────────────────────────────────────────
# ## 21 Crea una función que calcule el cubo de un número dado mediante una función lambda

# ────────────────────────────────────────────────────────────────────────
# %%  [44]

cubo = lambda x: x**3

cubo(2)

# ────────────────────────────────────────────────────────────────────────
# ## 22 Dada una lista numérica, obtén el producto total de los valores de dicha lista.Usa la función reduce() ## 
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [11]

def sum_lista (lista:list[int]) ->int:
    return reduce(lambda acum, x: acum + x, lista) # reduce va recorriendo la lista numero a numero y acumulando el resultado

# ────────────────────────────────────────────────────────────────────────
# %%  [46]

lista = (1, 5, 6, 7, 8)
print(sum_lista(lista))

# ────────────────────────────────────────────────────────────────────────
# ## 23 Concatena una lista de palabras.Usa la función reduce() ##

# ────────────────────────────────────────────────────────────────────────
# %%  [13]

def concat (lista_palabras: list[str]) -> str:
    return reduce (lambda acum, palabra: acum + palabra, lista_palabras)

# ────────────────────────────────────────────────────────────────────────
# %%  [14]

lista_palabras = ("Hola", "mi", "animal", "favorito", "es", "el", "perro")
concat(lista_palabras)

# ────────────────────────────────────────────────────────────────────────
# ## 24 Calcula la diferencia total en los valores de una lista. Usa la función reduce() . ##

# ────────────────────────────────────────────────────────────────────────
# %%  [15]

def diferencia_valores(lista:list[int]) -> int:
    return reduce(lambda acum, x: acum - x, lista) # reduce va reccoriendo la lista restando numero a numero y acumulando el resultado

# ────────────────────────────────────────────────────────────────────────
# %%  [19]

lista = [50, 20, 5, 1, 5]
print(diferencia_valores(lista))

# ────────────────────────────────────────────────────────────────────────
# ## 25 Crea una función que cuente el número de caracteres en una cadena de texto dada. ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [22]

def contar_caracteres (cadena: str):
    """Cuenta el número de caracteres la cadena de texto dada"""
        if isinstance(cadena, str):
            
            return f"La cadena de texto tiene un total de: {len(cadena)} caractere."
        else:
            raise TypeError("El argumento debe de ser una cadena de texto")
    

# ────────────────────────────────────────────────────────────────────────
# %%  [23]

contar_caracteres("Hola mundo, estoy haciendo una Kata de python")

# ────────────────────────────────────────────────────────────────────────
# ## 26 Crea una función lambda que calcule el resto de la división entre dos números dados. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [53]

resto = lambda x, y: x%y
resto(50, 10)

# ────────────────────────────────────────────────────────────────────────
# ## 27 Crea una función que calcule el promedio de una lista de números ##
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [30]

def media_num (lista: list[float]) ->float:
    
    return round(reduce(lambda acum, x: acum + x, lista) / len(lista),2)


# ────────────────────────────────────────────────────────────────────────
# %%  [31]

lista = (1, 6, 7, 8, 8, 6, 3)
media_num(lista)

# ────────────────────────────────────────────────────────────────────────
# ## 28 Crea una función que busque y devuelva el primer elemento duplicado en una lista dada.
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [56]

def busqueda_rep (lista):
    """Nos devuelve el primer valor que se encuentre repetido en una lista"""
    lista_append = []
    duplicado = []
    for x in lista:
        if x not in lista_append:
            lista_append.append(x)
        else:
            duplicado.append(x)
            break # rompe el bucle for para que solo devuelva un valor, el primer elemento duplicado

    return duplicado


# ────────────────────────────────────────────────────────────────────────
# %%  [57]

lista = ("Hola", 5, "reloj", "llaves", 3, "Pajaro", 3, "mochila")
print(busqueda_rep(lista))

# ────────────────────────────────────────────────────────────────────────
# ## 29 Crea una función que convierta una variable en una cadena de texto y enmascare todos los caracteres  con el carácter '#', excepto los últimos cuatro.

# ────────────────────────────────────────────────────────────────────────
# %%  [37]

def ocultar(cadena_texto):
    """oculta los valores de una cadena de texo menos los últims 4 valores"""
    
    cadena_texto = str(cadena_texto)
    almoadillas = (len(cadena_texto) - 4) * "#"
    texto = cadena_texto [-4:]
    cadena_oculta = almoadillas + texto
        
        
    return cadena_oculta
    

# ────────────────────────────────────────────────────────────────────────
# %%  [38]

ocultar("Contraseña")

# ────────────────────────────────────────────────────────────────────────
# ## 30 Crea una función que determine si dos palabras son anagramas, es decir, si están formadas por las mismas letras pero en diferente orden. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [58]

def anagrama (palabra_1: str, palabra_2: str):
    """Esta funcion compara dos palabras para ver si son anagramas, es decir, si tienen las mismas letras, pero en distinto orden """
    coinciden = []
    
    palabra_1 = palabra_1.lower()
    palabra_2 = palabra_2.lower()
    
    if len(palabra_1) == len(palabra_2): # comprueba si las palabras tienen el mismo tamaño
        
        for letra in palabra_1: 
                
            if letra in palabra_2:
                coinciden.append(letra) # si la letra está en las dos palabras la añade en la lista coincicden
            else:
                pass
                    
        if len(coinciden) == len(palabra_1): # si coinciden todas las letras es un anagrama
                
            resultado = f"La palabra {palabra_1} y la palabra {palabra_2} son anagramas"
        else: 
            resultado = f"La palabra {palabra_1} y la palabra {palabra_2} no son anagramas"
    else:
            resultado = f"La palabra {palabra_1} y la palabra {palabra_2} no son anagramas"
        
    return resultado


        
   

    

# ────────────────────────────────────────────────────────────────────────
# %%  [59]

anagrama("Pesticida", "Oreja")

# ────────────────────────────────────────────────────────────────────────
# ## 31 Crea una función que solicite al usuario ingresar una lista de nombres y luego solicite un nombre para buscar en esa lista. Si el nombre está en la lista, se imprime un mensaje indicando que fue encontrado, de lo contrario, se lanza una excepción. ##

# ────────────────────────────────────────────────────────────────────────
# %%  [39]

def buscador_nombre():
    
    lista_nombre = input("Por favor, añada una lista de nombres:").split(",") 
    lista_nombre_ = [nombre.strip().lower() for nombre in lista_nombre] #ponen los nombre de la lista en minúsculas

    nombre = input("Por vaor, añada un nombre a buscar:")
    if nombre.lower() in lista_nombre_: 
        return f"El nombre {nombre}  ha sido encontrado en la lista"
    else:
        raise Exception(f"{nombre} no se encuentra en la lista.")

# ────────────────────────────────────────────────────────────────────────
# %%  [41]

buscador_nombre()

# ────────────────────────────────────────────────────────────────────────
# ## 32 Crea una función que tome un nombre completo y una lista de empleados, busque el nombre completo en la lista y devuelve el puesto del empleado si está en la lista, de lo contrario, devuelve un mensaje indicando que la persona no trabaja aquí.

# ────────────────────────────────────────────────────────────────────────
# %%  [53]

class Empleado:
    """ Crea una clase donde crea empleados junto con información sobre el empleado {Nombre y posición}  """
    empleados = []
    
    def __init__(self, nombre, posición):
        self.nombre = nombre
        self.posición = posición
        Empleado.empleados.append(self) # agraga los empleados creados a una lista para luego poder llamarla
        
    

# ────────────────────────────────────────────────────────────────────────
# %%  [45]

Lola = Empleado("Lola", "reponedor")
Manuel = Empleado("Manuel", "Gerente")
Lucas = Empleado("Lucas", "Reponedor")
Javier = Empleado("Javier", "Cajero")
Sara = Empleado("Sara", "Administrativo")
Alba = Empleado("Alba", "Gerente")
Mario = Empleado("Mario", "Cajero")

# ────────────────────────────────────────────────────────────────────────
# %%  [51]

def buscador_empleados(nombre: str, empleados:list[dict]):
    
    for empleado in empleados: # Se crea un bucle que busca los nombres que hay en la lista para poder evaluar si se encunetra el nombre buscado
        if empleado.nombre == nombre: 
            return f"{nombre} trabaja como {empleado.posición}"
            
    return f"{Nombre} no trabaja aquí"
    

# ────────────────────────────────────────────────────────────────────────
# %%  [50]

buscador_empleados("Mario", Empleado.empleados)

# ────────────────────────────────────────────────────────────────────────
# ## 33 Crea una función lambda que sume elementos correspondientes de dos listas dadas.

# ────────────────────────────────────────────────────────────────────────
# %%  [69]

lista_1 = [1, 2, 4, 5, 6, 8]
lista_2 = [2, 1, 1, 1 ,1 ,1]

list(map(lambda x, y: x + y, lista_1, lista_2))

# ────────────────────────────────────────────────────────────────────────
# ## 34 Crea la clase árbol

# ────────────────────────────────────────────────────────────────────────
# %%  [71]

class árbol:
    """ Clase que crea un objeto (árbol) junto con varias funciones para el mantenimiento del árbol """
    def __init__(self, ramas:list = None, tronco: int = 1): # Creación de objeto árbol. De forma predeterminada el árbol tendrá 0 ramas y el tronco medirá 1cm
        self.ramas = [] if ramas is None else list(ramas) # si no se define en número de ramas crea lista vacia 
        self.tronco = tronco
         
    def crecer_tronco(self, crecimiento:int):
        self.tronco += crecimiento 
        return f"El árbol ha crecido {crecimiento} cm"

    
    def nueva_rama(self, n_ramas:int, tamaño_ramas = 1): 
        """ Crea una función donde se definen cuantas ramas le crecen al árbol y el tamaño de las ramas, de forma base cada rama crecerá 1cm"""
        for i in range(n_ramas):
            self.ramas.append(tamaño_ramas)
        return f"Al árbol le han crecido un total de {n_ramas} nuevas rama"
        
    def crecer_ramas(self, C_ramas:int = 1):
        """Crecen las ramas en el tamaño seleccionado, todas las ramas crecen por igual. De base crecrerán 1cm """
        self.ramas = list(map(lambda x: x + C_ramas, self.ramas))
        
        return [f"rama de {rama} cm" for rama in self.ramas]
        
    def quitar_rama(self, p_ramas:int = 0):
        self.ramas.pop(p_ramas) # p_ramas será la posición de la lista de ramas, si no se define la rama que se quiere quitar se quitará la primera rama
        
    def info_arbol(self):
        
        return f"El árbol tiene un total de {len(self.ramas)} ramas ({[f'rama de {rama} cm' for rama in self.ramas]}). El tronco mide {self.tronco} cm"

# ────────────────────────────────────────────────────────────────────────
# %%  [71]

manzano = árbol()

# ────────────────────────────────────────────────────────────────────────
# %%  [72]

manzano.crecer_tronco(1)

# ────────────────────────────────────────────────────────────────────────
# %%  [73]

manzano.nueva_rama(1)

# ────────────────────────────────────────────────────────────────────────
# %%  [74]

manzano.crecer_ramas()

# ────────────────────────────────────────────────────────────────────────
# %%  [75]

manzano.info_arbol()

# ────────────────────────────────────────────────────────────────────────
# %%  [76]

manzano.nueva_rama(2)

# ────────────────────────────────────────────────────────────────────────
# %%  [77]

manzano.quitar_rama(2)

# ────────────────────────────────────────────────────────────────────────
# %%  [78]

manzano.info_arbol()

# ────────────────────────────────────────────────────────────────────────
# ## 36 Crea la clase UsuarioBanco ,representa a un usuario de un banco con su nombre, saldo y si tiene o no cuenta corriente. Proporciona métodos para realizar operaciones como retirar dinero, transferir dinero desde otro usuario y agregar dinero al saldo.

# ────────────────────────────────────────────────────────────────────────
# %%  [90]

class UsuarioBanco:
    """Clase donde crea usuario de banco y funciones sobre la retirada, deposito o transferencia de dinenero en su cuenta bancaria """
    lista_usuarios =  []
    def __init__ (self, usuario:str, saldo:float, cc:bool = True):
        self.usuario = str(usuario)
        self.saldo = float(saldo)
        if not isinstance(cc, bool):
            raise ValueError("El valor de la cuenta corriente tiene que ser True o False")
        self.cc = cc
        UsuarioBanco.lista_usuarios.append(self)
        
    def retirar_dinero (self, dinero_retirado:float):
        
        if dinero_retirado <= self.saldo: #comprueba si el saldo del usuario e smayor o igual al saldo que se quiere retirar para eviar descubiertos
            
            self.saldo -= dinero_retirado
            
            print(f"El nuevo saldo de {self.usuario} es {self.saldo}€.")
            
        else: #Si no hay saldo suficiente no se permite la retirada de dinero
            
            raise Exception(f"{self.usuario} no tiene saldo sufieciente.")


    def trasferencia (self, usuario_destino:str, dinero_transferido:float):
        
        if dinero_transferido <= self.saldo:
            
            self.saldo -= dinero_transferido
            usuario_destino.saldo += dinero_transferido
            print(f"Transferencia realizada. El nuevo saldo de {self.usuario} es {self.saldo}€.")
            
        else: # si no hay saldo suficiente no se permite la transferencia de dinero
             
            raise Exception(f"{self.usuario} no tiene saldo sufieciente.") 
                      
    def agregar_dinero (self, dinero_sumado):
        self.saldo += dinero_sumado
        print(f"El nuevo saldo del usuario {self.usuario} es {self.saldo}€.")


# ────────────────────────────────────────────────────────────────────────
# %%  [91]

Bob = UsuarioBanco("Bob", 50)
Alicia = UsuarioBanco("Alicia", 100)

# ────────────────────────────────────────────────────────────────────────
# %%  [92]

for usuario in UsuarioBanco.lista_usuarios:
    print(usuario.usuario, usuario.saldo, usuario.cc)

# ────────────────────────────────────────────────────────────────────────
# %%  [93]

Bob.agregar_dinero(20)

# ────────────────────────────────────────────────────────────────────────
# %%  [94]

Bob.trasferencia(Alicia, 80)

# ────────────────────────────────────────────────────────────────────────
# %%  [95]

Alicia.retirar_dinero(50)

# ────────────────────────────────────────────────────────────────────────
# %%  [96]

for usuario in UsuarioBanco.lista_usuarios:
    print(usuario.usuario, usuario.saldo)

# ────────────────────────────────────────────────────────────────────────
# ## 37. Crea una función llamada procesar_texto que procesa un texto según la opción especificada: contar_palabras,reemplazar_palabras, eliminar_palabra . Estas opciones son otras funciones que tenemos que definir primero y llamar dentro de la función procesar_texto .
# 

# ────────────────────────────────────────────────────────────────────────
# Código a seguir:
# 
# - Crear una función contar_palabras para contar el número de veces que aparece cada palabra en el texto. Tiene 
# que devolver un diccionario.
#     
# - Crear una función reemplazar_palabras para remplazar una palabra_original del texto por una palabra_nueva
# Tiene que devolver el texto con el remplazo de palabras.
#     
# - Crear una función eliminar_palabra para eliminar una palabra del texto. Tiene que devolver el texto con la palabra 
# eliminada.
#  
# 
# 
# - Crear la función procesar_texto que tome un texto, una opción(entre "contar", "reemplazar", "eliminar") y un 
# número de argumentos variable según la opción indicada.
# 
# 
# Caso de uso:
# Comprueba el funcionamiento completo de la función 
# procesar_texto

# ────────────────────────────────────────────────────────────────────────
# %%  [98]

def contar_palabras (texto:str) -> dict[str, int]:
    """Cuenta las palabras que se encuentren en un texto dado """
    recuento = {}
    texto = texto.lower().split() # crea una lista con las palabras separadas convirtiendolas en minúsculas
    caracteres= (",",".",";",":","!","¡","?","¿") # cramos lista con caractéres para poder evitar contarlos
    texto_limpio= []

    for palabra in texto: # bucre for para eliminar los simbolos de puntuación
        for caracter in caracteres:
            palabra = palabra.replace(caracter, "") # si la "palabra" es un caracter se elimina
        texto_limpio.append(palabra) # si la palabra no es un caracter la agrega a la lista texto_limpio
        
    for palabra in texto_limpio: 
        if palabra in recuento:
            recuento[palabra] +=1
        else:
            recuento[palabra] = 1
            
    
    return recuento


# ────────────────────────────────────────────────────────────────────────
# %%  [99]

def remplazar_palabras(texto: str, p_reemplazar:str, p_remplazo:str) -> str:
    """esta función reemplaza una palabra seleccionada por otra, todas las veces que aparezca en un texto dado """
    texto = texto.split() #convierte el texto en una lista con todas las palabras en minúscula
    nuevo_texto = []

    for palabra in texto:
        
        palabra_limpia = palabra.strip(".,;:!?¡¿") #evitar errores cuando la palabra esá junto con un signo de puntuación. strip elimina los valores extremos
        puntuacion = palabra[len(palabra_limpia):] #guardamos la puntuación para poder añadirla posteriormente y que el texto no se vea alterado

        
        if palabra_limpia.lower() == p_reemplazar.lower():
            nuevo_texto.append(p_remplazo + puntuacion) # si la palabra iterada es igual a la palabra a reemplazar la sustituye por la palabra remplazo

        else:
            nuevo_texto.append(palabra)

    return " ".join(nuevo_texto) # convierte la lista nuevo texto en un str

# ────────────────────────────────────────────────────────────────────────
# %%  [100]

def elimiar_palabra(texto, p_eliminar):

    texto = texto.split()
    
    texto_filtrado = [palabra for palabra in texto if palabra.lower() != p_eliminar.lower()] # añade solo las palabras que sean distintas a la palabra a eliminar

    return " ".join(texto_filtrado)

# ────────────────────────────────────────────────────────────────────────
# %%  [101]

def procesar_texto (opción :str, *args):
    """ """
    
    if opción.lower() == "contar":
        return contar_palabras(args[0]) # el argumento será el texto

    if opción.lower() == "reemplazar":
        return remplazar_palabras(args[0], args[1], args[2]) # los argumentos erán el texto, la palabra a reemplazar y la palabra reemplazo

    if opción.lower() == "eliminar":
        return eliminar_palabra(args[0], args[1]) # los argumentos serñan el texto y la palabra a eliminar

    else:
        raise TypeError("La opción deberá ser una entre reemplazar, contar o eliminar")
        



# ────────────────────────────────────────────────────────────────────────
# %%  [102]

texto =( 
"""Tres Anillos para los Reyes Elfos bajo el cielo Siete para los Señores Enanos en palacios de piedra.
Nueve para los Hombres Mortales condenados a morir.
Uno para el Señor Oscuro, sobre el trono oscuro
en la Tierra de Mordor donde se extienden las Sombras.
Un Anillo para gobernarlos a todos.
Un Anillo para encontrarlos,
un Anillo para atraerlos a todos y atarlos en las tinieblas
en la Tierra de Mordor donde se extienden las Sombras. """)

# ────────────────────────────────────────────────────────────────────────
# %%  [103]

procesar_texto("contar", texto)

# ────────────────────────────────────────────────────────────────────────
# %%  [121]

procesar_texto("reemplazar", texto, "Anillos", "Rings")

# ────────────────────────────────────────────────────────────────────────
# ## 38 Genera un programa que nos diga si es de noche, de día o tarde según la hora proporcionada por el usuario.
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [106]

import datetime


Hora = (input("¿Qué hora es? introduce la hora (HH:MM)"))
Hora = datetime.datetime.strptime(Hora, "%H:%M")

if 5 <= Hora.hour < 12:
    
    print("Es por la mañana")
    
elif 12 <= Hora.hour < 21:
    
    print("Es por la tarde")

elif 21 <= Hora.hour <= 24 or 1 <= Hora.hour < 5:

    print("Es por la noche")








# ────────────────────────────────────────────────────────────────────────
# ## 39 Escribe un programa que determine qué calificación en texto tiene un alumno en base a su calificación numérica. 
#  Las reglas de calificación son:
#  
#  0 - 69 insuficiente
#  
#  70 -79 bien
#  
#  80 - 89 muy bien
#  
#  90 - 100 excelente
# 
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [54]

alumnos = [
{"Nombre" : "Juan",
 "Edad" : 30,
 "Calificación" : 90},
    
{"Nombre" : "Alberto",
 "Edad" : 25,
 "Calificación" : 87},
    
{"Nombre" : "Sofía",
 "Edad" : 27,
 "Calificación" : 100},
    
{"Nombre":"María F",
 "Edad" : 28,
 "Calificación" : 90},
    
{"Nombre" : "Alejandro",
 "Edad" : 29,
 "Calificación" : 70},
    
{"Nombre" : "Estefanía",
 "Edad" : 29,
 "Calificación" : 86},
    
{"Nombre" : "María G",
"Edad" : 27,
"Calificación" : 92}]


# ────────────────────────────────────────────────────────────────────────
# %%  [55]

for alumno in alumnos:
    
    if alumno["Calificación"] >= 0 and alumno["Calificación"] <= 69:
        
        alumno["Calificación_texto"] = "Insuficiente"
        
    elif alumno["Calificación"] >= 70 and alumno ["Calificación"] <= 79:
        
        alumno["Calificación_texto"] = "Bien"

    elif alumno["Calificación"] >= 80 and alumno ["Calificación"] <= 89:
        
        alumno["Calificación_texto"] = "Muy Bien"

    elif alumno["Calificación"] >= 90 and alumno ["Calificación"] <= 100:

        alumno["Calificación_texto"] = "Excelente"

    else:
        pass

# ────────────────────────────────────────────────────────────────────────
# %%  [56]

alumnos

# ────────────────────────────────────────────────────────────────────────
# ## 40  Escribe una función que tome dos parámetros: datos (una tupla con los datos necesarios para calcular el área de la figura). y figura (una cadena que puede ser "rectangulo" , "circulo" o "triangulo" )
# 

# ────────────────────────────────────────────────────────────────────────
# %%  [110]

import math


def areas (figura: str, *datos):
    """ La función calcula el área de tras posibles figuras geométricas: rectangulo, circulo y triangulo. 
    
    Para ello hay que elegir la figura y definir por orden la base y la altura. A excepción del ciruclo que se definira solo el radio"""
    
    figuras = ("rectangulo", "circulo", "triangulo")
    figura = figura.lower()
    pi = math.pi
    
    if figura == "rectangulo":
        base = float(datos[0])
        altura = float(datos[1])
        
        area = round(base * altura, 2)
        return f"El área del rectangulo es {area} cm^2"
            
    if figura == "circulo":
        radio = float(datos[0])
        
        area = round(pi * radio **2, 2)
        return f"El área del circulo es {area} cm^2"

    if figura == "triangulo":
        base = float(datos[0])
        altura = float(datos[1])
        
        area = round((base * altura)/2, 2)
        return f"El área del triangulo es {area} cm^2"
    else:
        raise Exception (f"Selecione una figura entre {figuras}")
        
        
        


# ────────────────────────────────────────────────────────────────────────
# %%  [111]

areas("triangulo", 5, 3)

# ────────────────────────────────────────────────────────────────────────
# %%  [112]

areas("circulo", 7)

# ────────────────────────────────────────────────────────────────────────
# ## 41 En este ejercicio, se te pedirá que escribas un programa en Python que utilice condicionales para determinar el monto final de una compra en una tienda en línea, después de aplicar un descuento.
# 
# 

# ────────────────────────────────────────────────────────────────────────
# 1. Solicita al usuario que ingrese el precio original de un artículo.
# 2. Pregunta al usuario si tiene un cupón de descuento (respuesta sí o no).
# 3. Si el usuario responde que sí, solicita que ingrese el valor del cupón de descuento.
# 4. Aplica el descuento al precio original del artículo, siempre y cuando el valor del cupón sea válido (es decir, mayor 
# a cero). Por ejemplo, descuento de 15€. 
# 5. Muestra el precio final de la compra, teniendo en cuenta el descuento aplicado o sin él. 
# 6. Recuerda utilizar estructuras de control de flujo como if, elif y else para llevar a cabo estas acciones en tu 
# programa de Python

# ────────────────────────────────────────────────────────────────────────
# %%  [113]

mensaje = "Por favor, introduce el precio del artículo:"
while True:
   
    try:
        articulo = float(input(mensaje))
        break #rompe el bucle while para seguir con el código una vez se haya añadido un valor numérico
    
    except ValueError:
        mensaje = "Por favor, introduce un valor numérico:"

resultado = ["si", "no"]
mensaje = "¿Tienes algun descuento?"

while True:
    
    descuento = input(mensaje).lower()
    
    if descuento in resultado:
        break
        
    mensaje = "Por vavor, diga si o no"

if descuento in resultado:
    
    if descuento == "si":
        
        mensaje ="Por favor, introduzca el valor del descuento:"
        
        while True:
            try:
                valor_descuento = float(input(mensaje))

                if valor_descuento > 0:
                
                    precio_final = articulo - valor_descuento
                    
                    break # rompe el bucle while una vez se haya añadido un descuento mayor a 0
                else:
                    mensaje = "Por favor, introduzca un descuento mayor a 0"
                
            except ValueError:
                mensaje = "Por favor, introduce un valor numérico:"
                
        print(f"El precio de la compra es igual a {precio_final} €")
              
    elif descuento == "no":
        
        print(f"El precio de la compra es igual a {articulo} €")
    
    
            
    
